#!/bin/bash

#Source directory to monitor
source_directory="/home/rps/Deskto/Assignment"

#Destinatio directory to store backups
backup_dir="/home/rps/Desktop"

#create backup directory if it doesn't exist
mkdir -p "$backup_dir"

#Infinite loop to continuously monitor the directory
while true; do

  #Get list of file in the source directory
   files=$(ls "$source_dir")

 #Loop through each file in the source directory
  for file in $files; do
   #check if the file is not a directory
    if [ -f "$source_dir/$file" ]; then

  #Check if the file is not already backup
   if [ ! -f "backup_dir/$file" ]; then

# COpyif the file to backup directory
cp "$source_dir/$file" "$backup_dir"
echo "Backup created for $file"
fi
fi
done
#sleep for a few second before checking again
slepp 5
 done
