#!/bin/bash

display_menu()
{
echo "Menu:"
echo "1. Add"
echo "2. Delete"
echo "3. View"
echo "4. Exit"
echo "Enter your choice:"

while true; do
display_menu
read choice

case $choice in

1)
  echo "Add selecter.";;

2)
  echo "Delet selected.";;

3)
  echo "View selected.";;

4) 
  echo "Exit.";;

*)
  echo "Invalid choice.";;

 esac
done
