#!/bin/bash

echo "Enter a password(at least 8 characters with  a mix of letters , numbers, and characters):"

while true; do 
 read -s password

if [[ ${#password} -ge 8 && "$password" != *[[:space:]]* ]]; then
echo "password accepted."
break

else 
echo "Password is not valid".

fi

done
