#!/bin/bash

echo "Please enter a positive number:"

while :

do
 read number
if [ $number -gt 0 2>/dev/null ]; then  #=[0-9]=$
echo "Thank you for entering a positive number: $number"
break
 else 
echo "Invalid input. Please enter the positive number"
fi
done
