#!/bin/bash

def print_num_lines(filename):
 with open (file, 'r') as file:
 line = file.readlines()
printf(f"Number of lines in {filename}:{len(lines)}")


print_num_lines("file1.txt")
print_num_lines("file2.txt")
printf_num_lines(file3.txt")
